steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image-a'
  args: ['build',
         '--cache-from', 'gcr.io/$PROJECT_ID/$_IMAGE_A:latest',
         '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_A:$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_A:latest',
         '.']
  dir: 'a'
logsBucket: ruckus-cloudbuilders-logs
substitutions:
    _IMAGE_A: 'a'
images:
    - 'gcr.io/$PROJECT_ID/$_IMAGE_A:$SHORT_SHA'
    - 'gcr.io/$PROJECT_ID/$_IMAGE_A:latest'
tags:
    - 'repo.$REPO_NAME'
    - 'branch.$BRANCH_NAME'
    - 'short_sha.$SHORT_SHA'
    - 'image.a'
