steps:
- name: 'ubuntu'
  args: [ 'env' ]
  env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'TAG_NAME=$TAG_NAME'
      - 'REVISION_ID=$REVISION_ID'
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-image-a'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_A:$SHORT_SHA', '.']
  dir: 'a'
logsBucket: ruckus-cloudbuilders-logs
substitutions:
    _IMAGE_A: 'a'
images:
    - 'gcr.io/$PROJECT_ID/$_IMAGE_A'
tags:
    - 'repo.$REPO_NAME'
    - 'branch.$BRANCH_NAME'
    - 'short_sha.$SHORT_SHA'
    - 'image.a'
